# Generated by Django 4.2.6 on 2023-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_id_alter_product_id_alter_review_id'),
        ('payment', '0002_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_in_order',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
