# Generated by Django 4.2.6 on 2023-10-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_products_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_in_order',
        ),
    ]
