# Generated by Django 4.2.6 on 2023-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('confirmed', 'Order Confirmed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='confirmed', max_length=50),
        ),
    ]
