# Generated by Django 4.2.6 on 2023-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='confidence',
            field=models.FloatField(),
        ),
    ]
